const EARTH=6371000; const rad=d=>d*Math.PI/180;
const distance=(a,b)=>{const p1=rad(a.lat),p2=rad(b.lat),dp=rad(b.lat-a.lat),dl=rad(b.lng-a.lng);const x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return EARTH*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));};
const bearing=(a,b)=>{const p1=rad(a.lat),p2=rad(b.lat),dl=rad(b.lng-a.lng);return (Math.atan2(Math.sin(dl)*Math.cos(p2),Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl))*180/Math.PI+360)%360;};
const delta=(a,b)=>((b-a+540)%360)-180;
function maneuver(a,b,c){const d=delta(bearing(a,b),bearing(b,c));if(Math.abs(d)<15)return 'STRAIGHT';if(Math.abs(d)>150)return 'U_TURN';if(d>55)return 'RIGHT';if(d<-55)return 'LEFT';if(d>15)return 'SLIGHT_RIGHT';return 'SLIGHT_LEFT';}
const labels={START:'出發',STRAIGHT:'直行',LEFT:'左轉',RIGHT:'右轉',SLIGHT_LEFT:'靠左行駛',SLIGHT_RIGHT:'靠右行駛',U_TURN:'迴轉',MERGE:'匯入車道',ROUNDABOUT:'進入圓環',ARRIVAL:'抵達目的地'};
export function buildGuidance(route){if(!route?.points?.length)return [];const pts=route.points,roads=route.roads||[],out=[];let along=0;for(let i=1;i<pts.length;i++){const seg=distance(pts[i-1],pts[i]);const road=roads[Math.min(i-1,roads.length-1)]||pts[i].name||'道路';const prevRoad=roads[Math.min(i-2,roads.length-1)];if(i===1)out.push({index:0,type:'START',label:'出發',road,distance:0,along:0});if(i>1&&(road!==prevRoad||i===pts.length-1)){const type=i===pts.length-1?'ARRIVAL':maneuver(pts[i-2],pts[i-1],pts[i]);out.push({index:i-1,type,label:labels[type]||type,road,distance:0,along});}along+=seg;}if(!out.some(x=>x.type==='ARRIVAL'))out.push({index:pts.length-1,type:'ARRIVAL',label:'抵達目的地',road:pts.at(-1)?.name||'目的地',distance:0,along});for(let i=0;i<out.length;i++)out[i].distance=Math.max(0,(out[i+1]?.along??route.distance)-out[i].along);return out;}
export function getCurrentGuidance(route,location){const list=buildGuidance(route);if(!list.length)return null;let best=list[0],min=Infinity;for(const item of list){const p=route.points[Math.min(item.index,route.points.length-1)];const d=distance(location,p);if(d<min){min=d;best=item;}}return {...best,remainingToManeuver:Math.max(0,best.distance)};}
export function laneFor(type,road=''){if(type==='ARRIVAL'||type==='START')return {lanes:['直行'],active:0,reason:type==='ARRIVAL'?'已抵達':'出發'};if(type==='LEFT'||type==='SLIGHT_LEFT')return {lanes:['左轉','直行','右轉'],active:0,reason:'提前靠左'};if(type==='RIGHT'||type==='SLIGHT_RIGHT')return {lanes:['左轉','直行','右轉'],active:2,reason:'提前靠右'};if(/快速|高速/.test(road))return {lanes:['直行','直行','匯出'],active:1,reason:'保持主線'};return {lanes:['左轉','直行','右轉'],active:1,reason:'保持中線'};}
export function iconFor(type){return {START:'●',STRAIGHT:'↑',LEFT:'↰',RIGHT:'↱',SLIGHT_LEFT:'↖',SLIGHT_RIGHT:'↗',U_TURN:'↶',ARRIVAL:'◎',MERGE:'⇢'}[type]||'↑';}
