import {getState,setState,subscribe} from './state.js';
import {OfflineRouter,routeToDestination} from './routing.js';
import {TrafficEngine} from './traffic.js';

export function mountRouting({panel,summary,preference,avoidHighway,avoidToll,avoidFerry,avoidUnpaved,routeBtn,alternativeBtn,clearBtn,map}){
  const traffic=new TrafficEngine();const router=new OfflineRouter('./data/routes.json',traffic);let lastDestination=null;let routeRequestGeneration=0;
  const destinationKey=d=>d?JSON.stringify([d.id||null,Number(d.lat),Number(d.lng),d._offlinePackageRecordId||null,d._offlinePackageId||null,d._offlinePackageVersion||null]):'';
  const selectedOptions=()=>({preference:preference.value,avoidHighway:avoidHighway.checked,avoidToll:avoidToll.checked,avoidFerry:avoidFerry.checked,avoidUnpaved:avoidUnpaved.checked});
  const render=state=>{const r=state.route;if(!r){summary.textContent='尚未規劃離線路線';return}const impacts=(r.edgeTraffic||[]).filter(x=>x.events?.length);summary.innerHTML=`<strong>${(r.distance/1000).toFixed(1)} km</strong> · 約 ${Math.max(1,Math.round(r.seconds/60))} 分鐘<br><small>${r.roads.join(' → ')}</small>${impacts.length?`<br><em>⚠ ${impacts.length} 個交通事件影響本路線</em>`:''}`;map.showRoute?.(r);};
  subscribe(async state=>{render(state);if(state.navigationStatus==='NAVIGATING'&&state.destination&&state.trafficEvents?.length){const generation=routeRequestGeneration;const routeId=state.route?.id;const destKey=destinationKey(state.destination);try{const r=await router.calculate({origin:state.currentLocation||{lat:25.0478,lng:121.5319},destination:state.destination,waypoints:state.waypoints?.map(w=>w.location||w)||[],...(state.route?.options||{})});const current=getState();if(generation===routeRequestGeneration&&current.navigationStatus==='NAVIGATING'&&destinationKey(current.destination)===destKey&&current.route?.id===routeId&&state.route?.id!==r.id)setState({route:{...r,destinationKey:state.route?.destinationKey,sourcePackageRecordId:state.route?.sourcePackageRecordId,sourcePackageId:state.route?.sourcePackageId,sourcePackageVersion:state.route?.sourcePackageVersion},alternativeRoutes:[r],remainingDistance:r.distance,remainingTime:r.seconds});}catch{}}});render(getState());
  routeBtn.addEventListener('click',async()=>{const s=getState();lastDestination=s.destination;if(!lastDestination){summary.textContent='請先從搜尋結果選擇目的地';return}routeBtn.disabled=true;const generation=++routeRequestGeneration;summary.textContent='正在使用離線路網計算…';try{await routeToDestination(router,lastDestination,selectedOptions());if(generation!==routeRequestGeneration)return}catch(e){summary.textContent=e.message||'離線算路失敗'}finally{routeBtn.disabled=false}});
  alternativeBtn.addEventListener('click',async()=>{const s=getState();if(!lastDestination)lastDestination=s.destination;if(!lastDestination){summary.textContent='請先選擇目的地';return}alternativeBtn.disabled=true;const generation=++routeRequestGeneration;const destKey=destinationKey(lastDestination);const routeIdAtStart=s.route?.id;summary.textContent='正在搜尋替代路線…';try{await traffic.refresh();const routes=await router.alternatives({origin:s.currentLocation||{lat:25.0478,lng:121.5319},destination:lastDestination,...selectedOptions()});const current=getState();if(generation!==routeRequestGeneration||destinationKey(current.destination)!==destKey||current.navigationStatus==='NAVIGATING'||current.route?.id!==routeIdAtStart)return;setState({alternativeRoutes:routes,route:{...routes[0],destinationKey:s.route?.destinationKey,sourcePackageRecordId:s.route?.sourcePackageRecordId,sourcePackageId:s.route?.sourcePackageId,sourcePackageVersion:s.route?.sourcePackageVersion},remainingDistance:routes[0].distance,remainingTime:routes[0].seconds});summary.innerHTML=routes.map((r,i)=>`<button class="route-choice" data-index="${i}">${i===0?'推薦':'替代 '+i} · ${(r.distance/1000).toFixed(1)} km · ${Math.round(r.seconds/60)} 分</button>`).join('');summary.querySelectorAll('.route-choice').forEach(b=>b.addEventListener('click',()=>{const r=routes[Number(b.dataset.index)];setState({route:r,remainingDistance:r.distance,remainingTime:r.seconds});map.showRoute?.(r)}));map.showRoute?.(routes[0]);}catch(e){summary.textContent=e.message||'替代路線搜尋失敗'}finally{alternativeBtn.disabled=false}});
  clearBtn.addEventListener('click',()=>{routeRequestGeneration++;lastDestination=null;setState({route:null,alternativeRoutes:[],remainingDistance:null,remainingTime:null,ETA:null,navigationStatus:'READY'});map.clearRoute?.()});
  panel.hidden=false;
}
