import {getState,setState,subscribe} from './state.js';
const EARTH=6371000, rad=d=>d*Math.PI/180;
function distance(a,b){const p1=rad(a.lat),p2=rad(b.lat),dp=rad(b.lat-a.lat),dl=rad(b.lng-a.lng);const x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return EARTH*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
function bearing(a,b){const p1=rad(a.lat),p2=rad(b.lat),dl=rad(b.lng-a.lng);return (Math.atan2(Math.sin(dl)*Math.cos(p2),Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl))*180/Math.PI+360)%360;}
function angular(a,b){return Math.abs(((a-b+540)%360)-180);}
function nearestAlong(point,points){let best={distance:Infinity,along:0};let total=0;for(let i=0;i<points.length-1;i++){const a=points[i],b=points[i+1],seg=distance(a,b);const t=Math.max(0,Math.min(1,((point.lng-a.lng)*(b.lng-a.lng)+(point.lat-a.lat)*(b.lat-a.lat))/((b.lng-a.lng)**2+(b.lat-a.lat)**2||1)));const q={lat:a.lat+(b.lat-a.lat)*t,lng:a.lng+(b.lng-a.lng)*t};const d=distance(point,q);if(d<best.distance)best={distance:d,along:total+seg*t};total+=seg;}best.total=total;return best;}
export class UpAheadEngine{
 constructor({placesUrl='./data/places.json',citiesUrl='./data/cities.json'}={}){this.placesUrl=placesUrl;this.citiesUrl=citiesUrl;this.places=null;this.cities=null;this.unsub=null;}
 async load(){if(!this.places)this.places=await fetch(this.placesUrl).then(r=>{if(!r.ok)throw new Error('離線 POI 資料無法載入');return r.json()});if(!this.cities)this.cities=await fetch(this.citiesUrl).then(r=>{if(!r.ok)throw new Error('離線城市資料無法載入');return r.json()});return this;}
 async init(){await this.load();this.unsub=subscribe(s=>this.update(s));this.update(getState());return this;}
 destroy(){this.unsub?.();}
 update(s){if(!s.currentLocation){return;}const route=s.route?.points?.length?s.route:null;const heading=s.heading||0;const max=12000;let pois=this.places.map(p=>({...p,_distance:distance(s.currentLocation,p),_bearing:bearing(s.currentLocation,p)})).filter(p=>p._distance<=max&&angular(heading,p._bearing)<=100);if(route){const here=nearestAlong(s.currentLocation,route);pois=pois.map(p=>{const a=nearestAlong(p,route);return {...p,_along:a.along,_corridor:a.distance}}).filter(p=>p._corridor<=850&&p._along>=here.along-50).sort((a,b)=>a._along-b._along||a._distance-b._distance);}else pois.sort((a,b)=>a._distance-b._distance);const upAhead=pois.slice(0,8).map(p=>({id:p.id,name:p.name,category:p.category,address:p.address,lat:p.lat,lng:p.lng,distance:Math.round(p._distance),bearing:Math.round(p._bearing),rating:p.rating,tags:p.tags}));let cities=this.cities.map(c=>({...c,_distance:distance(s.currentLocation,c),_bearing:bearing(s.currentLocation,c)})).filter(c=>c._distance<=30000&&angular(heading,c._bearing)<=110);if(route){const here=nearestAlong(s.currentLocation,route);cities=cities.map(c=>({...c,_along:nearestAlong(c,route).along,_corridor:nearestAlong(c,route).distance})).filter(c=>c._corridor<=1800&&c._along>=here.along-100).sort((a,b)=>a._along-b._along);}else cities.sort((a,b)=>a._distance-b._distance);const citiesAhead=cities.slice(0,5).map(c=>({id:c.id,name:c.name,type:c.type,description:c.description,distance:Math.round(c._distance)}));setState({nearbyPOIs:upAhead,citiesAhead});}
}
export function formatDistance(m){return m<1000?`${m} m`:`${(m/1000).toFixed(1)} km`;}
